### ISSUE TITLE
Convert to PEM format

### ISSUE THREAD

**Issue by allRiceOnMe** [NVISOsecurity/MagiskTrustUserCerts#1]
It would be better, if the certificate would be converted to PEM before copying it. This would be equivalent to the format of the certificates in the system certificate store.

A working guidance is linked [here](https://jamie.holdings/2016/09/04/Installing-a-new-trusted-SSL-root-certificate-on-Android.html). However, the `SHA1 Fingerprint=` at the end of the certificate is still missing when following this guidance.

**Comment by TheDauntless** [comment]
Is there a specific reason why it would be better, apart from consistency? Are there any use cases where the current setup wouldn't work?

**Comment by freeload101** [comment]
FYI this is how I convert to PEM in windows without openssl 

https://github.com/freeload101/Java-Android-Magisk-Burp-Objection-Root-Emulator-Easy/blob/38f8f1b6ece96d7f442ae2f58f6284e27d5399ba/JAMBOREE.ps1#L266

```
Write-Host "[+] Converting "$VARCD\BURP.der" to "$VARCD\BURP.pem""
Remove-Item -Path "$VARCD\BURP.pem" -Force -ErrorAction SilentlyContinue |Out-Null
Start-Process -FilePath "$env:SYSTEMROOT\System32\certutil.exe" -ArgumentList  " -encode `"$VARCD\BURP.der`"  `"$VARCD\BURP.pem`" "  -NoNewWindow -Wait

Write-Host "[+] Copying PEM to Androind format just in case its not standard burp suite cert Subject Hash 9a5ba575.0"
# Rename a PEM in Android format (openssl -subject_hash_old ) with just certutil and powershell
$CertSubjectHash = (certutil "$VARCD\BURP.der")
$CertSubjectHash = $CertSubjectHash |Select-String  -Pattern 'Subject:.*' -AllMatches  -Context 1, 8
$CertSubjectHash = ($CertSubjectHash.Context.PostContext[7]).SubString(24,2)+($CertSubjectHash.Context.PostContext[7]).SubString(22,2)+($CertSubjectHash.Context.PostContext[7]).SubString(20,2)+($CertSubjectHash.Context.PostContext[7]).SubString(18,2)+"."+0
Copy-Item -Path "$VARCD\BURP.pem" -Destination "$VARCD\$CertSubjectHash" -Force
```
