### ISSUE TITLE
Updater process ended with ERROR:1

### ISSUE THREAD

**Issue by Dentrax** [NVISOsecurity/MagiskTrustUserCerts#16]
I've just downloaded latest [v0.4.1](https://github.com/NVISO-BE/MagiskTrustUserCerts/releases/tag/v0.4.1) `.zip` file. And tried the flash on Magisk. But process resulted with non-zero exit code: `Updater process ended with ERROR:1`

`Android 10 - MIUI 12`

I just followed the [install](https://github.com/NVISO-BE/MagiskTrustUserCerts#installation) instructions. Did i missing something?

**Comment by TheDauntless** [comment]
Which version of Magisk do you have? Is there any info in the Magisk Logs?
