### ISSUE TITLE
 the logo page will always be stuck when the phone is restarted in android 11

### ISSUE THREAD

**Issue by barcelona-messi** [NVISOsecurity/MagiskTrustUserCerts#21]
After the installation is completed on the OnePlus Android 11 device, the logo page will always be stuck when the phone is restarted

**Comment by TheDauntless** [comment]
@barcelona-messi  as I don't have a OnePlus device, I can't test this. Are you able to collect any logs as per https://www.didgeridoohan.com/magisk/MagiskHelp ?

Can you also check if the paths used in the module actually exist?
* /system/etc/security/cacerts
* /data/misc/user/0/cacerts-added/
