### ISSUE TITLE
Update for android 10+ ?

### ISSUE THREAD

**Issue by ayuschatterjee** [NVISOsecurity/MagiskTrustUserCerts#26]
The module doesn't seem to work on android 10+ versions.

**Comment by afaq1337** [comment]
Not working on Android 9 as well. 

**Test Configs:**

- Pixel 3 Stock
- Android 9
- Magisk 25.1
- Module Version v0.4.1

**Comment by freeload101** [comment]
v0.4.1
Supports Android 10

Let me know if you get it to work .. I am working on a portable lajit android /MITM builder thingy for windows ...

**Comment by afaq1337** [comment]
@freeload101, It works on Android 10!!
Thanks,

**Comment by ardzz** [comment]
what about on android 12?

**Comment by prashantwosti-crypto** [comment]
any plans for android 12 compatibility? thanks

**Comment by prashantwosti** [comment]
any plans for android 12 compatibility? thanks

**Comment by icew4y** [comment]
I have no idea why it didn't work on your devices of whatever android 9-12, but it worked very well on my devices(I have all of the versions of devices).

**Comment by SekiBetu** [comment]
> any plans for android 12 compatibility? thanks

i'm using android 12, it's working on my phone, i actually can do this functions my self, it's just few commands, if the directory where the Android certificate is stored remains the same, there is no need to be compatible with the new version of Android

**Comment by freeload101** [comment]
> The module doesn't seem to work on android 10+ versions.
> 

Works for me!!!

Java Android Magisk Burp Objection Root Emulator Easy (JAMBOREE) 

https://github.com/freeload101/Java-Android-Magisk-Burp-Objection-Root-Emulator-Easy

**Comment by ConstasJ** [comment]
Is it work for Windows Subsystem for Android?

**Comment by freeload101** [comment]
> Is it work for Windows Subsystem for Android?

my ps1 script ... this  repo is for any Android OS ... as for my script you don't need WSL... just run the ps1 script its all in the link
