### ISSUE TITLE
Does not install user certificate on android 9

### ISSUE THREAD

**Issue by Wheaties466** [NVISOsecurity/MagiskTrustUserCerts#8]
I am fully rooted on a oneplus 5 with android 9( OOS 9.04) and It will not add the user cert to the system certificates.

Any assistance would be appreciated. I can provide logs if told where to find them.

**Comment by ruodezizaiyi** [comment]
the same problem in mi9 with android Q

**Comment by harrisonwhiskey** [comment]
Doesn't work on android 10 too

**Comment by illnino** [comment]
> Doesn't work on android 10 too
> 
> Edit:
> i'm sorry i wasn't patient before but it works on android 10. after installing the cert you have to restart your phone.
> 
> Here is where i got confused, after the cert has been added to your system certs your user certs will still be there giving you the network may be monitored warning.

Hi harrisonwhiskey 

May I ask if you are using Emulator or real device? My Pixel 3a running on Android 10 failed to install user certificates to system even after restart.

My other phones running on Android 9 or lower work fine.

**Comment by Wheaties466** [comment]
@illnino i was never able to get it working even after reboot on android 9
