### ISSUE TITLE
Does not work on 8.1.0 Lineage on Galaxy S2

### ISSUE THREAD

**Issue by fr33wi11** [NVISOsecurity/MagiskTrustUserCerts#9]
First of all after Install in Magisk  modules version shown is v0.2-- though I made sure to download and install v0.3.

Under trusted credential still certificate is under User and not removed (after reboot).

Also not go moved/copied to System

Its magisk 20.3 manager 7.5.1

Any thoughts/fixes?

**Comment by shoeper** [comment]
It looks like it also stopped working on my phone. But I currently don't know whether the apps I tried to intercept had certificate pinning or not.

**Comment by TheDauntless** [comment]
Can you check v0.4.1 from the releases?

**Comment by sg552** [comment]
You should make sure that your "Magisk" is updated ( current latest version is 20.4 ).

Just now I also met the same problem , and at that time, my Magisk version is 7.0 .  then I click the "update" button on its landing page , then update to the latest version, this module worked !
